name: cache npm
on: pull_request
jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js 
        uses: actions/setup-node@v3 
        with: 
          node-version: 16.16.0
          
  # Caching these reduces download time.
  # Dependencies are fetched from Github's cloud instead in one go.
  # Path for windows is: %AppData%/npm-cache for macOS/Linux it is: ~/.npm.
  # See 'https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows' 
  
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
        
      - name: Make directory for npm package
        run: mkdir my-npm-pkg
        
      - name: Change to directory
        run: cd my-npm-pkg
        
      - name: Initialise package.json
        run: npm init -y

      - name: Install AXIOS dependencies
        run: npm ci axios@0.27.2 --save
      
      - name: Install CHEERIO dependencies 
        run: npm ci cheerio@1.0.0-rc.12 --save
        
      - name: Install EXPRESS dependencies 
        run: npm ci express@4.18.1 --save
        
      - name: Install MONGOOSE dependencies
        run: npm ci mongoose@6.5.0 --save
        

      
  
