name: Move assigned issue card 

# Deals with only assigned issues.
on: 
  issues:
    types: [opened]

# Moves opened issue card to in progress column.
jobs:
  move-assigned-issue-card:
    runs-on: [self-hosted, windows, x64]
    steps:
          - name: Move assigned issues to in progress
          - uses: checkout/actions@v1
          - uses: ./.github/workflows/move-assigned-issue
            with:
              project: 'REST-API-Project'
              column: 'In progress'
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: main

                          
